Check point 1
KatsiarynaZhukava/phoneshop pull request #1
Opened 2021-08-04 08:40 UTC by KatsiarynaZhukava

2021-08-07 01:43 UTC, WladyslawDryhill requested changes
Check point 1 review

2021-08-07 01:43 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/ColorRowMapper.java
> +    private static final Set<Color> existingColors = Collections.synchronizedSet(new HashSet<>());
Для лучшей производительности давай заменим Set на подходящую реализацию Map и вместо итерации по сету будем доставать Color по ключу (id)

2021-08-07 01:43 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/ColorRowMapper.java
> +        if (maybeColor.isPresent()) {
При работе с Optional лучше избегать явных проверок на isPresent() и придерживаться функционального подхода, давай заменим явную проверку на Optional#orElseGet

2021-08-07 01:43 UTC, WladyslawDryhill commented on web/src/main/webapp/WEB-INF/applicationContext.xml
> +    <context:component-scan base-package="com.es.phoneshop.web" />
Сканирование компонентов в пакете com.es.phoneshop.web уже включено в dispatcher-servlet.xml и в принципе нет смысла его дублировать

2021-08-07 01:43 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/PhoneWithColorsExtractor.java
> +            Phone phone = phones.stream()
В принципе согласен, потери в производительности от создания нескольких новых соединений с БД серьезнее, чем фильтрация дубликатов. Давай оставим одну кверю с джоином и не будем переделывать на две квери, но здесь для более эффективного хранения и проверки уникальных значений лучше использовать HashMap, а не итерацию по сету

2021-08-07 01:43 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/PhoneWithColorsExtractor.java
> +                phone = new BeanPropertyRowMapper<>(Phone.class).mapRow(resultSet, resultSet.getRow());
При каждой итерации создается новый объект маппера, предлагаю вынести его на уровень поля в классе и переиспользовать

2021-08-07 01:43 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/PhoneWithColorsExtractor.java
> +                Color color = new ColorRowMapper().mapRow(resultSet, resultSet.getRow());
То же самое что и в прошлом случае - лучше вынести на уровень поля и переиспользовать

2021-08-07 01:43 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        if (offset < 0) throw new InvalidParameterException("Offset must be >= 0");
Исключение специфичное для пакета java.security, давай заменим на что-то более универсальное, например IllegalArgumentException

2021-08-07 01:43 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/PhoneWithColorsExtractor.java
> +        List<Phone> phones = new ArrayList();
Diamond оператор пропущен, надо поправить на ArrayList<>()

2021-08-07 01:43 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +                                                new Object[] { key }, new PhoneWithColorsExtractor());
У экстрактора нет состояния так что я бы его тоже вынес на уровень поля и переиспользовал

2021-08-07 01:43 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        return phones.stream().findFirst();
Создавать стрим для поиска первого элемента не очень эффективно, предлагаю проверить пустой ли список и просто вернуть нулевой элемент

2021-08-07 01:43 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +                                  new Object[] { offset, limit }, new PhoneWithColorsExtractor());
Тут как и в прошлом случае надо переиспользовать один объект экстрактора

2021-08-07 01:43 UTC, WladyslawDryhill commented on web/src/main/webapp/WEB-INF/conf/application.properties
> -# TODO
Давай вернем проперти файл в web модуль, как обсуждали сегодня

2021-08-07 01:43 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        Optional<Phone> foundPhone = get(phone.getId());
Давай все же оставим обновление записи в БД если телефон уже существует. Однако для проверки на наличие телефона я бы использовал отдельную кверю вида "select 1 from phones where id = ?" дабы не тянуть лишние данные из БД, и вынес выполнение этой квери в отдельный метод с сигнатурой вида boolean exists(Long id)

2021-08-07 01:43 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +                    SimpleJdbcInsert simpleJdbcInsert = new SimpleJdbcInsert(jdbcTemplate).withTableName("phones").usingGeneratedKeyColumns("id");
Объект SimpleJdbcInsert может быть переиспользован и вынесен на уровень поля

2021-08-07 01:43 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +            throw new InvalidParameterException("Invalid parameter: a phone with such brand and model value combination already exists");
Лучше использовать универсальный IllegalArgumentException

2021-08-07 01:43 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +    public void save( final Phone phone ) {
В виду того что в методе save происходит сразу несколько зависящих друг от друга взаимодействий с БД (проверка на наличие телефона в базе -> вставка либо обновление в зависимости от результата) было бы неплохо потренироваться минимизировать возможные проблемы от параллельной вставки новых записей. Давай попробуем обернуть выполнение метода save в одну транзакцию (посмотри как настроить аннотацию @ Transactional, это довольно просто). Если мы выставим этой транзакции уровень изоляции REPEATABLE_READ то исключим вероятность того что после проверки на наличие телефона какая-либо другая транзакция успеет вставить телефон с таким же id и наш метод упадет с исключением

2021-08-08 13:25 UTC, WladyslawDryhill commented on web/src/main/webapp/WEB-INF/applicationContext.xml
> +    <context:component-scan base-package="com.es.phoneshop.web" />
**Fixed**

2021-08-08 16:32 UTC, WladyslawDryhill requested changes
Еще немножко поправок и будет отлично

2021-08-08 16:32 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/ColorRowMapper.java
> +    private static final Map<Long, Color> existingColors = Collections.synchronizedMap(new HashMap<>());
Я бы рекомендовал использовать ConcurrentHashMap вместо синхронизированной обертки, т.к. обертка имеет всего один lock (сам объект коллекции) на все операции и следовательно операции чтения и записи могут блокировать друг друга. У ConcurrentHashMap чтение не блокирующее.

2021-08-08 16:32 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/ColorRowMapper.java
> +        Color color = existingColors.getOrDefault(colorId, new Color(colorId, resultSet.getString("code")));
Каждый раз при вызове этого метода создается новый лишний объект Color, даже если в мапе уже лежит такой же цвет. Рекомендую здесь использовать метод Map#computeIfAbsent и передавать функцию по созданию нового объекта Color которая во-первых будет иметь отложенное выполнение (только в случае если подходящего цвета нет) и во-вторых будет сразу добавлять объект в мапу и возвращать его.

2021-08-08 16:32 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/PhoneWithColorsExtractor.java
> +            Phone phone = phones.getOrDefault(id, phoneBeanPropertyRowMapper.mapRow(resultSet, resultSet.getRow()));
Тут тоже подойдет Map#computeIfAbsent дабы не вызывать каждый раз phoneBeanPropertyRowMapper#mapRow

2021-08-08 16:32 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +            if (exists(phone.getId())) {
Думаю проверку id на null нужно сделать перед тем как искать существующий телефон по id

2021-08-08 16:32 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +                    simpleJdbcInsert.withTableName("phones").usingGeneratedKeyColumns("id");
Думаю не стоит объект SimpleJdbcInsert создавать в контексте спринга. Для полной его инициализации недостаточно вызова конструктора и после первого запроса у объекта вызывается метод SimpleJdbcInsert#compile после которого изменение его конфигурации будет приводить к исключению, т.е. нормально переиспользовать где-то еще мы его не сможем. Также при повторном вызове метода save при попытке второй раз изменить его конфигурацию метод будет падать с исключением. Рекомендую не создавать SimpleJdbcInsert в контейнере спринга, а создать его самостоятельно через new в поле класса JdbcPhoneDao, а также проинициализировать его либо в конструкторе JdbcPhoneDao либо в блоке инициализации как-то так:
`simpleJdbcInsert.withTableName("phones")
.usingGeneratedKeyColumns("id")
.compile()`
Тогда мы сможем вызывать save повторно без исключений.

2021-08-08 16:32 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +    private boolean exists( Long id ) {
Думаю имеет смысл этот метод сделать public и вынести в интерфейс PhoneDao, а также добавить для него отдельный тест в JdbcPhoneDaoIntTest

2021-08-09 02:17 UTC, KatsiarynaZhukava commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +                    simpleJdbcInsert.withTableName("phones").usingGeneratedKeyColumns("id");
Может, просто добавить в метод проверку на simpleJdbcInsert.isCompiled? Конструктор требует параметром объект JdbcTemplate, который ко времени вызова конструктора ещё не создан

2021-08-09 02:36 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +                    simpleJdbcInsert.withTableName("phones").usingGeneratedKeyColumns("id");
Точно, давай тогда лучше полную инициализацию simpleJdbcInsert вплоть до вызова compile() сделаем в своём собственном методе для инициализации и пометим его аннотацией @PostConstruct, в таком случае спринг вызовет его один раз после того как все зависимости будут уже заинжекчены.

2021-08-09 03:00 UTC, KatsiarynaZhukava commented on core/src/main/java/com/es/core/model/phone/PhoneWithColorsExtractor.java
> +
Не знаю какой здесь лучше эксепшн кинуть: свой создать или какой-то из dao заюзать?

2021-08-09 03:54 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/PhoneWithColorsExtractor.java
> +
Упс, не заметил там checked исключение, у лямбд с ними есть определенные проблемы. Давай тогда забьем на computeIfAbsent и сделаем по-простому: сперва достаем Phone из мапки по ключу, и только в случае если возвращается null создаем с помощью маппера новый объект Phone и кладем в мапу. От предыдущей проблемы избавимся и не надо будет громоздить try catch блоки

2021-08-09 08:39 UTC, WladyslawDryhill requested changes
Вот теперь точно последние

2021-08-09 08:39 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/PhoneWithColorsExtractor.java
>          return new ArrayList(phones.values());
Еще поправь тут пожалуйста на ArrayList<>(...)

2021-08-09 08:39 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +    private SimpleJdbcInsert simpleJdbcInsert;
И тут я все же категорически советую убрать simpleJdbcInsert из контейнера спринга, просто создай его через new в методе initializeSimpleJdbcInsert. Потому что представь ситуацию если кто-то решит его переиспользовать в пределах проекта заметив этот бин в контексте, и в результате мы получим абсолютно непредсказуемую ситуацию где непонятно где вообще происходит его инициализация, и непредсказуемые ошибки если кто-то решит законфигурить его в другом своем бине. Лучше пусть этот объект будет привязан чисто к объекту нашего DAO.

2021-08-09 09:19 UTC, WladyslawDryhill approved these changes
Отлично, спасибо. Но у меня нет прав мержить почему-то

2021-08-09 10:01 UTC, merged