Check point 3
KatsiarynaZhukava/phoneshop pull request #5
Opened 2021-08-23 10:07 UTC by KatsiarynaZhukava

2021-08-24 21:34 UTC, WladyslawDryhill requested changes
Check point 3 review

2021-08-24 21:34 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/service/HttpSessionCartService.java
> +
Не могу написать на нужной строчке, напоминалочка про то чтобы отрефакторить немного получение cart totals, чтобы вместо отдельных методов getTotalQuantity и getTotalCost у нас был один метод (например getCartTotals) который вычислял бы эти значения с одной копии корзины и возвращал в одном каком-то DTO объекте

2021-08-24 21:34 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/service/HttpSessionCartService.java
> +                        throw new OutOfStockException(itemKey, requestedStock, availableStock);
Исключение посреди цикла прервет выполнение следующих итераций и в результате часть корзины обновится, а часть останется не обновленной и даже не проверенной на стоки. Предлагаю сперва проверить все айтемы на стоки и в случае если есть айтемы где не хватает стока - бросать одно исключение и хранить в нем список телефонов (или айдишников) из которого мы потом сможем забиндить сообщения об ошибке для каждого телефона. В случае исключения можно не обновлять корзину вообще.

2021-08-24 21:34 UTC, WladyslawDryhill commented on web/src/main/java/com/es/phoneshop/web/dto/input/CartItemInputDto.java
>      public void setRequestedQuantity(Long requestedQuantity) {
Напоминалочка про то чтобы попробовать настроить messageSource и в случае отключения джаваскрипта в браузере вывести сообщение для type mismatch.

2021-08-24 21:34 UTC, WladyslawDryhill commented on web/src/main/java/com/es/phoneshop/web/validation/QuantityValidator.java
> +            Long stockAvailable = stockDao.get(item.getPhoneId()).map(Stock::getStock).orElse(0L);
Можно получить стоки для всех телефонов в одном запросе.

2021-08-24 21:34 UTC, WladyslawDryhill commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +    @PostMapping(value = "/{phoneId}")
Можно использовать метод DELETE

2021-08-24 21:34 UTC, WladyslawDryhill commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        return "cart";
Дабы избежать повторной отправки формы лучше сделать редирект на GET запрос, результаты валидации можно прокинуть с помощью redirect attribute.

2021-08-24 21:34 UTC, WladyslawDryhill commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        List<Phone> phones = phoneDao.findAll(new ArrayList<>(cart.getItems().keySet()));
Имеет смысл в начале метода сделать копию корзины, чтобы избежать непредвиденных исключений типа NullPointerException, а также непредсказуемых результатов. Кроме того, расчет cart totals нужно будет тоже сделать на той же самой копии (думаю надо будет создать дополнительный метод в CartService который будет на вход принимать ту самую копию и возвращать cart totals).

2021-08-25 12:33 UTC, KatsiarynaZhukava commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +                                                                   e.getItems().get(0).getStockRequested(), e.getItems().get(0).getStockAvailable()));
OutOfStockException немного странный получился: если где-то в коде при его создании передать в конструктор пустой список OutOfStockItem-ов, то будет брошен IndexOutOfBoundsException, и никакое сообщение не отобразится.  Я не знаю, как лучше реализовать OutOfStockException

2021-08-25 20:51 UTC, WladyslawDryhill commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +                                                                   e.getItems().get(0).getStockRequested(), e.getItems().get(0).getStockAvailable()));
На самом деле в такой ситуации нас не должно волновать что кто-то может додуматься передать туда пустой список, это ошибка самого программиста и для этого в принципе и существуют unchecked исключения. Однако я бы все же немного отрефакторил OutOfStockException и логику работы с ним:
1) добавил бы отдельный конструктор для случая когда у нас всего один телефон, чтоб инкапсулировать создание списка
2) добавил бы в оба конструктора генерацию дефолтного сообщения, т.к. сейчас там getMessage будет возвращать null, а кто знает где это исключение в будущем еще может логироваться к примеру. тогда в AjaxCartController-е можно было бы прокинуть просто сообщение из getMessage, ну а для нескольких конечно придется создавать для каждого отдельно, а дефолтным сообщением сделать какое-то обобщенное сообщение

2021-08-26 08:54 UTC, WladyslawDryhill requested changes
Еще немножко

2021-08-26 08:54 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/exception/OutOfStockException.java
> +    public static class OutOfStockItem {
Думаю имеет смысл сделать это обычным DTO классом, а не nested, т.к. он используется в других классах и по сути здесь инкапсуляции нет.

2021-08-26 08:54 UTC, WladyslawDryhill commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        model.addAttribute("cart", cartService.getCartTotalsOutputDto());
Здесь нужно передать копию созданную строчкой выше.

2021-08-26 08:54 UTC, WladyslawDryhill commented on web/src/main/java/com/es/phoneshop/web/validation/QuantityValidator.java
> +        Map<Long, Stock> stocks = stockDao.findAll( new ArrayList<>(items.stream().map(CartItemInputDto::getPhoneId).collect(Collectors.toList())))
toList() сам по себе создает ArrayList, а здесь получается создается снаружи еще один лишний ArrayList через copy-constructor

2021-08-26 08:54 UTC, WladyslawDryhill commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +                for ( OutOfStockException.OutOfStockItem item: e.getItems() ) {
Здесь у нас выходит 2 вложенных цикла (for each + indexOf), плюс каждый раз создается лишний объект CartItemInputDto для поиска. Думаю эффективнее будет сперва собрать все OutOfStockItem в мапку (phoneId, OutOfStockItem) за O(n) и потом через обычный цикл for тоже за O(n) пройтись по CartInputDto.getItems() и в случае если в мапке с OOS айтемами есть такой телефон то реджектать поле формы.

2021-08-26 08:54 UTC, WladyslawDryhill commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +                                              MessageFormat.format( "The overall requested stock {0} exceeds the available {1}",
В принципе это сообщение у нас используется сразу и в эксепшене и здесь, опционально можно создать какой-нибудь класс с константами типа PhoneShopConstants и хранить подобные сообщения там, и использовать константу оттуда и здесь и в эксепшене

2021-08-26 15:50 UTC, WladyslawDryhill approved these changes
Отлично

2021-08-26 15:50 UTC, merged