Check point 4
KatsiarynaZhukava/phoneshop pull request #6
Opened 2021-08-28 18:03 UTC by KatsiarynaZhukava

2021-08-31 20:18 UTC, WladyslawDryhill requested changes
Checkpoint 4 review

2021-08-31 20:18 UTC, WladyslawDryhill commented on core/src/test/resources/db/schema.sql
> +  subtotal FLOAT NOT NULL,
Я бы советовал для полей где хранятся денежные значения использовать decimal с фиксированной точностью до 2х знаков после запятой

2021-08-31 20:18 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/dao/JdbcOrderDao.java
> +            BeanPropertySqlParameterSource parameterSource = new BeanPropertySqlParameterSource(order) {
Валится ошибка из-за того что в таблице orders нет поля totalPrice

2021-08-31 20:18 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/dao/JdbcOrderDao.java
> +            Object[] values = new Object[]{ orderItem.getPhone().getId(), orderItem.getOrder().getId(), orderItem.getQuantity() };
Было бы неплохо кроме количества хранить еще и цену телефона на момент покупки, чтобы история заказов оставалась актуальной

2021-08-31 20:18 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/dao/JdbcStockDao.java
> +        jdbcTemplate.batchUpdate(UPDATE_STOCKS_QUERY, batch);
Тут я бы подумал как можно отловить эксепшен(ы) от нарушения check contraint-а и удалить телефоны, которые стали out of stock, иначе в таком случае будет редирект на страницу с ошибкой.

2021-08-31 20:18 UTC, WladyslawDryhill commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +                cartService.clearCart();
Т.к. мы не лочили корзину во время создания ордера то имеет смысл не полностью очищать корзину, а отнимать от текущей корзины (предварительно залочив) ту копию которую мы заказали.

2021-08-31 20:18 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/service/OrderServiceImpl.java
> +                orderItems.add(new OrderItem(null, phone, order, cartItem.getValue()));
Напоминалочка про сохранение текущей цены

2021-08-31 20:18 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/service/OrderServiceImpl.java
> +        order.setSecureId(UUID.randomUUID().toString());
Касательно secure id, предлагаю не сохранять его в базу данных. Вместо того, чтобы доставать ордер по секюр айди из БД на ордер овервью странице, предлагаю после размещения заказа генерировать этот айдишник и класть в сессию мапку типа <String, Order> (где ключом будет этот секюрный айдишник), и потом на ордер овервью странице ордер по этому айдишнику будет доставаться из сессии, а не из БД. Соответственно страница просмотра заказа будет доступна только на время существования сессии.

2021-08-31 22:34 UTC, WladyslawDryhill requested changes
Еще одну штуку заметил

2021-08-31 22:34 UTC, WladyslawDryhill commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        if (bindingResult.hasErrors()) {
Вот тут еще стоит на всякий случай сделать проверку на то пустая ли корзина, мало ли кто-то решит напрямую форму отправить.

2021-09-01 11:36 UTC, KatsiarynaZhukava commented on core/src/main/java/com/es/core/service/OrderServiceImpl.java
> +                } catch (DataIntegrityViolationException e) {
Я думала может если возникнет constraint violation отловить этот эксепшн и заново проверить стоки, или может по отдельности апдейтить айтемы в stockDao, ловить этот эксепшн там и собирать там еще outOfStock айтемы? Хотя наверное и так и так дичь какая-то получается

2021-09-02 22:15 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/service/OrderServiceImpl.java
> +                } catch (DataIntegrityViolationException e) {
Первый вариант крутой, тогда будет всего один лишний запрос на все стоки корзины сразу, потом удаление и возврат сообщения о том что некоторые товары были удалены. Лучше так, чем делать по одному запросу на каждый айтем.

2021-09-02 22:24 UTC, WladyslawDryhill requested changes
Еще парочка моментов

2021-09-02 22:24 UTC, WladyslawDryhill commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +                if (ordersWithUUIDsMap == null) ordersWithUUIDsMap = new HashMap<>();
Т.к. атрибуты сессии могут использоваться сразу несколькими потоками то лучше ConcurrentHashMap

2021-09-02 22:24 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/service/OrderServiceImpl.java
>          order.setSubtotal(cartService.getTotalCost(cartItems));
Тут можно посчитать сабтотал по только что созданным ордер айтемам, которые уже содержат цену телефонов на момент покупки. Иначе в методе cartService#getTotalCost делается еще один лишний запрос на цены телефонов.

2021-09-02 22:24 UTC, WladyslawDryhill commented on web/src/main/webapp/WEB-INF/pages/orderOverview.jsp
> +          <td>$ ${item.phone.price}</td>
Поменяй тут пожалуйста, чтоб бралась не актуальная цена телефона, а из item.purchaseTimePrice

2021-09-02 22:24 UTC, WladyslawDryhill commented on web/src/main/webapp/WEB-INF/pages/order.jsp
> +            <td>$ ${item.phone.price}</td>
И тут тоже

2021-09-03 19:26 UTC, WladyslawDryhill approved these changes
Круто, спасибо

2021-09-03 19:27 UTC, merged