Check point 5
KatsiarynaZhukava/phoneshop pull request #7
Opened 2021-09-05 14:07 UTC by KatsiarynaZhukava

2021-09-07 21:11 UTC, WladyslawDryhill requested changes
Checkpoint 5 review

2021-09-07 21:11 UTC, WladyslawDryhill commented on web/src/main/java/com/es/phoneshop/web/controller/pages/admin/AdminOrderPageController.java
> +        orderService.changeOrderStatus(order, orderStatus);
Как и обсуждали тут можно сделать проверку на то, что текущий статус ордера = NEW, иначе менять статус запрещается и редирект с 400м статусом.

2021-09-07 21:11 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/model/order/Order.java
>  public class Order {
Давай сделаем Order и вложенные типы Serializable, чтобы Tomcat мог нормально сохранять сессию в файловую систему.

2021-09-07 21:11 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/service/OrderServiceImpl.java
> +            stockDao.decreaseStock(requestedStocks);
Предлагаю сделать эти две операции в один запрос, чтобы уменьшить количество подключений к БД.

2021-09-07 21:11 UTC, WladyslawDryhill commented on core/src/main/java/com/es/core/service/OrderServiceImpl.java
> +        orderDao.save(order);
_Опционально:_ может быть немного эффективнее если вместо обновления всех полей ордера сразу сделать отдельную кверю на обновление только лишь статуса.

2021-09-08 18:02 UTC, KatsiarynaZhukava commented on web/src/main/java/com/es/phoneshop/web/controller/pages/admin/AdminOrderPageController.java
> +        orderService.changeOrderStatus(order, orderStatus);
Я не очень понимаю как можно отправить редирект с 400м статусом

2021-09-09 21:54 UTC, WladyslawDryhill approved these changes
✓

2021-09-09 21:54 UTC, merged